replicaCount: 1

image:
  repository: test-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

service:
  port: 4444

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  - name: HTTP_PORT
    value: "4444"
  - name: DB_DSN
    valueFrom:
      secretKeyRef:
        name: test-server-db
        key: dsn

livenessProbe:
  tcpSocket:
    port: 4444
  periodSeconds: 5

startupProbe:
  tcpSocket:
    port: 4444
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5 