name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Set image tag
      id: set-tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_ENV

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        token_format: 'access_token'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
        location: ${{ vars.GKE_CLUSTER_LOCATION }}

    - name: Deploy/Upgrade Helm chart
      env:
        HELM_EXPERIMENTAL_OCI: 1
        IMAGE_TAG: ${{ env.tag }}
      run: |
        echo ${{ steps.auth.outputs.access_token }} | helm registry login -u oauth2accesstoken --password-stdin ${{ vars.DOCKER_REGISTRY }}
        helm upgrade --install test-server \
          oci://${{ vars.HELM_REGIDTRY }}/charts/test-server \
          --namespace test-server \
          --atomic \
          --timeout 5m \
          --set image.tag=${IMAGE_TAG}
    
    - name: Verify deployment
      run: |
        kubectl --namespace test-server wait --for=condition=available deployment/test-server --timeout=3m 