name: Helm Chart

on:
  push:
    paths:
      - 'helm-charts/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push-chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Package Helm chart
      run: |
        helm package helm-charts/test_server

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Helm chart
      run: |
        helm push test-server-*.tgz oci://ghcr.io/${{ github.repository }}/charts 